# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: brain.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62rain.proto\x12\x06protos\":\n\x0f\x41llNeuronsQuery\x12\x10\n\x08timestep\x18\x01 \x01(\r\x12\x15\n\rsimulation_id\x18\x02 \x01(\r\"=\n\x06Neuron\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0f\n\x07\x63\x61lcium\x18\x02 \x01(\r\x12\x16\n\x0e\x66ired_fraction\x18\x03 \x01(\x02\".\n\x0bNeuronReply\x12\x1f\n\x07neurons\x18\x01 \x03(\x0b\x32\x0e.protos.Neuron\";\n\x10\x41llSynapsesQuery\x12\x10\n\x08timestep\x18\x01 \x01(\r\x12\x15\n\rsimulation_id\x18\x02 \x01(\r\"9\n\x07Synapse\x12\x0f\n\x07\x66rom_id\x18\x01 \x01(\r\x12\r\n\x05to_id\x18\x02 \x01(\r\x12\x0e\n\x06weight\x18\x03 \x01(\r\"1\n\x0cSynapseReply\x12!\n\x08synapses\x18\x01 \x03(\x0b\x32\x0f.protos.Synapse2\x86\x01\n\x05\x42rain\x12<\n\nAllNeurons\x12\x17.protos.AllNeuronsQuery\x1a\x13.protos.NeuronReply\"\x00\x12?\n\x0b\x41llSynapses\x12\x18.protos.AllSynapsesQuery\x1a\x14.protos.SynapseReply\"\x00\x42\x08Z\x06./grpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brain_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006./grpc'
  _ALLNEURONSQUERY._serialized_start=23
  _ALLNEURONSQUERY._serialized_end=81
  _NEURON._serialized_start=83
  _NEURON._serialized_end=144
  _NEURONREPLY._serialized_start=146
  _NEURONREPLY._serialized_end=192
  _ALLSYNAPSESQUERY._serialized_start=194
  _ALLSYNAPSESQUERY._serialized_end=253
  _SYNAPSE._serialized_start=255
  _SYNAPSE._serialized_end=312
  _SYNAPSEREPLY._serialized_start=314
  _SYNAPSEREPLY._serialized_end=363
  _BRAIN._serialized_start=366
  _BRAIN._serialized_end=500
# @@protoc_insertion_point(module_scope)
