version: "3.9"

services:
  gobrain:
    build: ./goserver
    ports:
      - 50052:50052
  gobrain-dev:
    build: ./goserver
    profiles: ["dev"]
    ports:
      - 50053:50053
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data_vol:/data/db
    container_name: mongo_container
    deploy:
      resources:
        limits:
          memory: 32G
        reservations:
          memory: 20G
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    container_name: redis_container

volumes:
  mongo_data_vol:
