// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: server/mock.proto

package server

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Mock_Stratum_FullMethodName = "/server.Mock/Stratum"
)

// MockClient is the client API for Mock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockClient interface {
	Stratum(ctx context.Context, in *StratumQuery, opts ...grpc.CallOption) (*Response, error)
}

type mockClient struct {
	cc grpc.ClientConnInterface
}

func NewMockClient(cc grpc.ClientConnInterface) MockClient {
	return &mockClient{cc}
}

func (c *mockClient) Stratum(ctx context.Context, in *StratumQuery, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Mock_Stratum_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockServer is the server API for Mock service.
// All implementations must embed UnimplementedMockServer
// for forward compatibility
type MockServer interface {
	Stratum(context.Context, *StratumQuery) (*Response, error)
	mustEmbedUnimplementedMockServer()
}

// UnimplementedMockServer must be embedded to have forward compatible implementations.
type UnimplementedMockServer struct {
}

func (UnimplementedMockServer) Stratum(context.Context, *StratumQuery) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stratum not implemented")
}
func (UnimplementedMockServer) mustEmbedUnimplementedMockServer() {}

// UnsafeMockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockServer will
// result in compilation errors.
type UnsafeMockServer interface {
	mustEmbedUnimplementedMockServer()
}

func RegisterMockServer(s grpc.ServiceRegistrar, srv MockServer) {
	s.RegisterService(&Mock_ServiceDesc, srv)
}

func _Mock_Stratum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StratumQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServer).Stratum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mock_Stratum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServer).Stratum(ctx, req.(*StratumQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// Mock_ServiceDesc is the grpc.ServiceDesc for Mock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.Mock",
	HandlerType: (*MockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stratum",
			Handler:    _Mock_Stratum_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/mock.proto",
}
